ferm/ferm/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("firn.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

ferm/firn/urls.py
from re import template
from django.urls import path
from . import views
from .models import Item
from django.conf import settings
from django.db.models import Avg
from django.conf.urls.static import static

home_list_view= views.HomeListView.as_view(
    queryset={'itens_hp':Item.objects.filter(categoria__nome="Higiene Pessoal").annotate(av=Avg('avaliacao__nota'))[:5],
              'itens_ca':Item.objects.filter(categoria__nome="Cosmeticos")[:5],
              'itens_me':Item.objects.filter(categoria__nome="Medicamentos")[:5],
              'itens_fi':Item.objects.filter(categoria__nome="Fitness")[:5]}.items(),
    context_object_name="itens",
    template_name="firn/home.html"
)

loja_list_view = views.LojaListView.as_view(
    queryset=Item.objects.all(),
    context_object_name='itens',
    template_name='firn/loja.html'
)

cart_list_view = views.CartListView.as_view(
    context_object_name='itens',
    template_name='firn/cart.html'
)


urlpatterns = [
    path("", home_list_view, name="home"),
    path("loja", loja_list_view, name="loja"),
    path("sobre", views.sobre, name="sobre"),
    path("carrinho", cart_list_view, name="cart"),
    path("a",views.a,name="a")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ferm/firn/models.py
from distutils.command.upload import upload
from email.policy import default
from tkinter import CASCADE
from unicodedata import decimal
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

class Item(models.Model):
    nome = models.CharField(max_length=200)
    preco = models.DecimalField(max_digits=6,decimal_places=2)
    descricao = models.TextField(default=None, null=True)
    quantidade = models.IntegerField(null=True,blank=True,default=None)
    imagem = models.ImageField(upload_to='items',null=True,blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Avaliacao(models.Model):
    nota = models.IntegerField()
    descricao = models.TextField(default=None,null=True,blank=True)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    
    def __str__(self):
        return "Av " + self.item.nome

ferm/firn/forms.py
from django import forms
from django.forms import NumberInput,HiddenInput
from .models import Item

class QtdForm(forms.Form):
    id = forms.IntegerField(widget=forms.HiddenInput())
    quantidade = forms.IntegerField(label='Quantidade',min_value=1)

    

ferm/firn/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import ListView
from .forms import QtdForm
from .models import Item
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def a(request):
    return render(request,'firn/angular_layout.html')

def sobre(request):
    return render(request,'firn/sobre.html')

class HomeListView(ListView):
    model = Item
    
    def get_context_data(self, **kwargs):
        context=super(HomeListView,self).get_context_data(**kwargs)
        context['result'] = self.request.GET.get('result', '') # default to empty string if not in GET data
        context['carr'] = len(self.request.session.items())
        context['form']=QtdForm()
        return context

    def post(self, request, *args, **kwargs):
        # context = self.get_context_data(**kwargs)
        qtdForm = QtdForm(self.request.POST)
        if qtdForm.is_valid():
            self.request.session[qtdForm['id'].value()]={
                'id':qtdForm['id'].value(),
                'quantidade':qtdForm['quantidade'].value()}
            return HttpResponseRedirect("?result=sucesso")
        else:
            return HttpResponseRedirect("?result=erro")
    
class LojaListView(ListView):
    paginate_by = 12
    model = Item
    
    def post(self, request, *args, **kwargs):
        # context = self.get_context_data(**kwargs)
        qtdForm = QtdForm(self.request.POST)
        if qtdForm.is_valid():
            self.request.session[qtdForm['id'].value()]={
                'id':qtdForm['id'].value(),
                'quantidade':qtdForm['quantidade'].value()}
            return HttpResponseRedirect("?result=sucesso")
        else:
            return HttpResponseRedirect("?result=erro")
    
    def get_context_data(self, **kwargs):
        context=super(LojaListView,self).get_context_data(**kwargs)
        context['form']=QtdForm()
        context['result'] = self.request.GET.get('result', '')
        context['carr'] = len(self.request.session.items())
        return context

class CartListView(ListView):
    model = Item
    paginate_by = 12
    
    def post(self, request, *args, **kwargs):
        return HttpResponse(self.request.POST.items())

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["carr"] = len(self.request.session.items())
        context["cart"] = dict(self.request.session.items())
        return context

    def get_queryset(self):
        queryset=Item.objects.filter(id__in=list(self.request.session.keys())),
        return queryset[0]
    

ferm/firn/templates/firn/angular_layout.html
<html>
    <head>
        {% load static %}

        <link rel="stylesheet" href="{% static 'firn/ang/ang/dist/ang/styles.ef46db3751d8e999.css' %}"></head>
    </head>
    <body>

        <app-root>
                
        </app-root>
        
        <script src="{% static 'firn/ang/ang/dist/ang/runtime.6dbd5b8cb9cfa392.js' %}" type="module"></script>
        <script src="{% static 'firn/ang/ang/dist/ang/polyfills.0f15e4a1de5caded.js' %}" type="module"></script>
        <script src="{% static 'firn/ang/ang/dist/ang/main.ddd6f0ef87d714e7.js' %}" type="module"></script>

    </body>
</html>

ferm/firn/templates/firn/cart.html
{% extends 'firn/layout.html' %}
{% block title %}
    Carrinho
{% endblock %}
{% block content %}
    {% load static %}
    {% load firn_extras %}
    <h3 class="text-second sub-titulo">Carrinho</h3>
    {% if carr %}
    <form method="POST">
    <div class="bd">
    <div class="packet side inline">
        {% csrf_token %}
            <table class="tabler">
            {% for item in itens %}
            <tr class="item-second">
                <td class="item-second-bl" style="width:120px; height:140px">
                    <img src="{{item.imagem.url}}" class="img-second">
                </td>
                <td class="item-second-bl sider">
                    <p class="text-second">{{item.nome}}</p>
                    <div class="rodape-card text-second">
                        <p>R$: {{ item.preco }}</p>
                    </div>
                </td>
                <td class="item-second-bl sider" >
                    <p>Quantidade:</p>
                    <input name="id{{item.id}}" type="hidden" value="{{item.id}}">
                    <input name="qtd{{item.id}}" class="sider-input" type="number" value="{{cart|get_item:item.id|get_item:"quantidade"}}" readonly>
                </td>
            </tr>
            {% endfor %}
            </table>
            </form>
        </div>

    
        <div class="packet side inline">

            <h3 class="sub-titulo">Dados De Pagamento</h3>
            <p>Total: R${{itens|get_item_sum_all:cart}}</p>
            
            <input class="button-qtd" type="submit" value="Realizar Compra">
        </div>
    </div>
    </form>

    {% else %}
        <p>Você não possui itens no seu carrinho ainda!</p>
    {% endif %}
{% endblock %}

ferm/firn/templates/firn/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Bem-Vindo A Fermacia</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'firn/styles/main.css' %}"/>
    <link rel="icon" type="image/icon type" href="{% static 'firn/img/logo.ico'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/be5f423282.js" crossorigin="anonymous"></script>

</head>

<body>

    {% if result %}

        {% if result == "sucesso" %}
            <dialog id="dialog-result" class="dialg success" open="">
                <div class="dialg-div">
                    <p style="padding:2px"><b>Sucesso!</b> item adicionado ao carrinho com sucesso!</p>  
                </div>
        {% else %}
        <dialog id="dialog-result" class="dialg fail" open="">
            <div class="dialg-div">
                <p style="padding:2px"><b>Erro!</b> ocorreu algum problema ao adicionar ao carrinho!</p>  
            </div>
        {% endif %}
            
            <div class="dialg-div">
                <button id="hide" class="dialg-btn" onClick="fechar()">X</button> 
            </div>
        </dialog>

    {% endif %}
    <div class="navbar">
        <img class="navbar-item logo" src="{% static 'firn/img/logo.png'%}">
        <a href="{% url 'home' %}" class="navbar-brand">Home</a>
        <a href="{% url 'loja' %}" class="navbar-item">Loja</a>
        <a href="{% url 'sobre' %}" class="navbar-item">Sobre</a>
        {{result}}
    </div>

<div class="body-content">

    <img src="{% static 'firn/img/lab.jpg'%}" class="img-main">

    <div class='packet'>
    
        <h3 class="text-main sub-titulo">Serviços para você</h3>

        <p class='text-main'>Aqui na Fermacia faremos o melhor para lhe proporcionar uma experiência que prioriza suas necessidades,
            a entrega personalizada para você.
        </p>

    </div>

    {% for k,v in itens %}
    <div class="packet">
        <h3 class="text-main sub-titulo">{{ v.0.categoria }}</h3>

        {% for item in v %}

            <div class="card">
                <p>{{item}}</p>
                {% if item.imagem%}
                <img class="img-card" src="{{item.imagem.url}}">
                {% else%}
                <img class="img-card" src="{% static 'firn/img/logo.png'%}">
                {% endif %}
                <p>R$: {{ item.preco }}</p>
                <div class="rodape-card">
                    {% if item.av %}
                        {% for a in '12345'|make_list %}
                                {% if a|add:"0" <= item.av %}
                                    <span class="fa fa-star checked"></span>
                                {% else%}
                                    <span class="fa fa-star"></span>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                          
                            {{ form.non_field_errors }}
                          
                            {{ form.source.errors }}
                            {{ form.source }}

                            {{ form.quantidade.errors }}
                            {% if item.quantidade %}
                                <input type="hidden" name="id" id="id_id" value="{{ item.id }}" required>
                                <input class="item-card input-qtd" type="number" name="quantidade" id="id_quantidade" min="1" max="{{item.quantidade}}" required>
                                <button class="item-card button-qtd" type="submit"><i class="fa-solid fa-cart-shopping"></i></button>
                            {% else %}
                                <button class="item-card button-qtd" type="submit" Disabled>Esgotado</button>
                            {% endif %}
                        </form>
                </div>
            </div>
            <a></a>
        {% endfor %}
    </div>
    {% endfor %}

    <hr/>
    <footer>
        <p class="text-rodape">&copy; 2022</p>
    </footer>
    <script src="{% static 'firn/dig.js' %}"></script>
</div>
</body>
</html>

ferm/firn/templates/firn/home_bk.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Bem-Vindo A Fermacia</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'firn/styles/main.css' %}"/>
    <link rel="icon" type="image/icon type" href="{% static 'firn/img/logo.ico'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/be5f423282.js" crossorigin="anonymous"></script>

</head>

<body>

    {% if result %}

        {% if result == "sucesso" %}
            <dialog id="dialog-result" class="dialg success" open="">
                <div class="dialg-div">
                    <p style="padding:2px"><b>Sucesso!</b> item adicionado ao carrinho com sucesso!</p>  
                </div>
        {% else %}
        <dialog id="dialog-result" class="dialg fail" open="">
            <div class="dialg-div">
                <p style="padding:2px"><b>Erro!</b> ocorreu algum problema ao adicionar ao carrinho!</p>  
            </div>
        {% endif %}
            
            <div class="dialg-div">
                <button id="hide" class="dialg-btn" onClick="fechar()">X</button> 
            </div>
        </dialog>

    {% endif %}
    <div class="navbar">
        <img class="navbar-item logo" src="{% static 'firn/img/logo.png'%}">
        <a href="{% url 'home' %}" class="navbar-brand">Home</a>
        <a href="{% url 'loja' %}" class="navbar-item">Loja</a>
        <a href="{% url 'sobre' %}" class="navbar-item">Sobre</a>
        {{result}}
    </div>

<div class="body-content">

    <img src="{% static 'firn/img/lab.jpg'%}" class="img-main">

    <div class='packet'>
    
        <h3 class="text-main sub-titulo">Serviços para você</h3>

        <p class='text-main'>Aqui na Fermacia faremos o melhor para lhe proporcionar uma experiência que prioriza suas necessidades,
            a entrega personalizada para você.
        </p>

    </div>

    {% for k,v in itens %}
    <div class="packet">
        <h3 class="text-main sub-titulo">{{ v.0.categoria }}</h3>

        {% for item in v %}

            <div class="card">
                <p>{{item}}</p>
                {% if item.imagem%}
                <img class="img-card" src="{{item.imagem.url}}">
                {% else%}
                <img class="img-card" src="{% static 'firn/img/logo.png'%}">
                {% endif %}
                <p>R$: {{ item.preco }}</p>
                <div class="rodape-card">
                    {% if item.av %}
                        {% for a in '12345'|make_list %}
                                {% if a|add:"0" <= item.av %}
                                    <span class="fa fa-star checked"></span>
                                {% else%}
                                    <span class="fa fa-star"></span>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                          
                            {{ form.non_field_errors }}
                          
                            {{ form.source.errors }}
                            {{ form.source }}

                            {{ form.quantidade.errors }}
                            {% if item.quantidade %}
                                <input type="hidden" name="id" id="id_id" value="{{ item.id }}" required>
                                <input class="item-card input-qtd" type="number" name="quantidade" id="id_quantidade" min="1" max="{{item.quantidade}}" required>
                                <button class="item-card button-qtd" type="submit"><i class="fa-solid fa-cart-shopping"></i></button>
                            {% else %}
                                <button class="item-card button-qtd" type="submit" Disabled>Esgotado</button>
                            {% endif %}
                        </form>
                </div>
            </div>
            <a></a>
        {% endfor %}
    </div>
    {% endfor %}

    <hr/>
    <footer>
        <p class="text-rodape">&copy; 2022</p>
    </footer>
    <script src="{% static 'firn/dig.js' %}"></script>
</div>
</body>
</html>